# -*- coding: utf-8 -*-
"""Untitled7 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vooRb0FUoRU5r83I3Y74hWzvah1KD-ZP
"""

import pandas as pd

from google.colab import drive

# Load the CSV
drive.mount('/content/drive')
input_file = "/content/drive/MyDrive/train5.parquet"
df = pd.read_parquet(input_file)

print(df.columns)

print(df['source'].value_counts())

df_binary = df[df['source'].isin(['human', 'ai'])].copy()

df_binary['label'] = df_binary['source'].map({'human': 0, 'ai': 1})

from sklearn.model_selection import train_test_split

X = df_binary['text']
y = df_binary['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features=2000)

# Fill missing values with empty strings before vectorizing
X_train_vec = vectorizer.fit_transform(X_train.fillna(''))
X_test_vec = vectorizer.transform(X_test.fillna(''))

from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

from sklearn.metrics import accuracy_score, classification_report

models = {'Naive Bayes': nb}

for name, model in models.items():
    y_pred = model.predict(X_test_vec)
    print(f"---{name}---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the model
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

# Train the model
rf.fit(X_train_vec, y_train)

# Predict on the test set
y_pred_rf = rf.predict(X_test_vec)

# Evaluate the model
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=10, random_state=42)
dt.fit(X_train_vec, y_train)

y_pred_dt = dt.predict(X_test_vec)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

from sklearn.svm import LinearSVC

svm = LinearSVC()
svm.fit(X_train_vec, y_train)

y_pred_svm = svm.predict(X_test_vec)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_vec, y_train)

y_pred_knn = knn.predict(X_test_vec)

print("K-NN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize the model
lr = LogisticRegression(max_iter=1000, random_state=42)

# Train the model
lr.fit(X_train_vec, y_train)

# Predict on the test set
y_pred_lr = lr.predict(X_test_vec)

# Evaluate the model
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

accuracies = {}

# Example after each model
accuracies["K-NN"] = accuracy_score(y_test, y_pred_knn)
accuracies["Logistic Regression"] = accuracy_score(y_test, y_pred_lr)
accuracies["Random Forest"] = accuracy_score(y_test, y_pred_rf)
accuracies["SVM"] = accuracy_score(y_test, y_pred_svm)
accuracies["Decision Tree"] = accuracy_score(y_test, y_pred_dt)

import matplotlib.pyplot as plt

# Extract algorithm names and their accuracies
models = list(accuracies.keys())
scores = list(accuracies.values())

# Plot
plt.figure(figsize=(10, 6))
plt.bar(models, scores, color='skyblue')
plt.ylim(0, 1)
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.xticks(rotation=30)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the score above each bar
for i, v in enumerate(scores):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

"""1. Preprocessing: Tokenization with Tokenizer"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Initialize tokenizer and fit
tokenizer = Tokenizer(num_words=20000, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

# Convert text to sequences
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

# Pad sequences to make them equal length
X_train_pad = pad_sequences(X_train_seq, maxlen=200)
X_test_pad = pad_sequences(X_test_seq, maxlen=200)

"""Convert Labels"""

import numpy as np
y_train = np.array(y_train)
y_test = np.array(y_test)

"""LSTM Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

model = Sequential()
model.add(Embedding(input_dim=20000, output_dim=128, input_length=200))
model.add(LSTM(64, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(X_train_pad, y_train, epochs=5, batch_size=64, validation_data=(X_test_pad, y_test))

loss, accuracy = model.evaluate(X_test_pad, y_test)
print("Test Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_pred_lstm = model.predict(X_test_pad)
y_pred_lstm_classes = (y_pred_lstm > 0.5).astype(int)

cm_lstm = confusion_matrix(y_test, y_pred_lstm_classes)
disp_lstm = ConfusionMatrixDisplay(confusion_matrix=cm_lstm, display_labels=['Human', 'AI'])

disp_lstm.plot(cmap='Reds')
plt.title("Confusion Matrix - LSTM")
plt.show()

# Logistic Regression
y_prob_lr = lr.predict_proba(X_test_vec)[:, 1]

# Naive Bayes
y_prob_nb = nb.predict_proba(X_test_vec)[:, 1]

# Random Forest
y_prob_rf = rf.predict_proba(X_test_vec)[:, 1]

# K-Nearest Neighbors
y_prob_knn = knn.predict_proba(X_test_vec)[:, 1]

# Decision Tree
y_prob_dt = dt.predict_proba(X_test_vec)[:, 1]
y_score_svm = svm.decision_function(X_test_vec)
y_prob_lstm = model.predict(X_test_pad).ravel()
prob_scores = {
    "Logistic Regression": y_prob_lr,
    "Naive Bayes": y_prob_nb,
    "Random Forest": y_prob_rf,
    "K-NN": y_prob_knn,
    "Decision Tree": y_prob_dt,
    "SVM": y_score_svm,       # or y_prob_svm if calibrated
    "LSTM": y_prob_lstm
}

from sklearn.metrics import roc_curve, roc_auc_score

fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
roc_auc_score(y_test, y_prob_lr)  # yields a number between 0 and 1

import matplotlib.pyplot as plt

# Prepare data
curves = {}
for name, clf in models.items():
    if hasattr(clf, "predict_proba"):
        y_prob = clf.predict_proba(X_test_vec)[:,1]
    else:
        y_prob = clf.decision_function(X_test_vec)
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc_val = roc_auc_score(y_test, y_prob)
    curves[name] = (fpr, tpr, auc_val)

# Plot
plt.figure(figsize=(8, 6))
for name, (fpr, tpr, auc_val) in curves.items():
    plt.plot(fpr, tpr, label=f"{name} (AUC = {auc_val:.2f})")

plt.plot([0, 1], [0, 1], "k--", label="No Skill (AUC = 0.50)")
plt.xlim([0.0, 1.0]); plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves for All Models")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()